### ISSUE TITLE
Not understanding update-listener and all the requests to individual docs

### ISSUE THREAD

**Issue by regner** [redgeoff/spiegel#149]
Hello o/,

We have a couchdb cluster with ~17,000 databases. Many of those DBs have between 15,000 and 20,000 docs, some of them have even more docs.

When I run the update-listerner our cluster gets absolutely smashed with requests for `/some-database/some-document?revs=true&open_revs=some_rev_id&latest=true`.

My questions are:
1) What are those requests for compared to watching the `_global_changes` feed?
2) Is there a way to limit the requests in any way?

Thanks in advance for your help and for creating Spiegel.

**Comment by redgeoff** [comment]
Hey @regner. This seems strange as Spiegel doesn't directly issue calls like this. If you are sure that the calls are not coming from your software then my guess it these calls are internal to CouchDB and coming from either the replications or listening to _changes feeds. I would suspect that this is an initialization thing: when Spiegel first runs it needs to iterate through all the _changes feeds for all the DBs so that it can apply whatever on_change docs are defined and then save the last seq numbers. After this initialization completes the _changes feed for a specific DB will only be checked when that DB changes.

If you are worried about the load, you can run Spiegel during off-peak hours, stop it during on-peak hours and repeat this process until it is done. Spiegel will automatically resume even if it is terminated abruptly.

**Comment by regner** [comment]
This will require some more research then. The requests for those docs did not appear to be coming from couch and this was from a DB server that is a replica of production for testing spiegel, meaning nothing else is reading/writing to it.

Will let you know what I find out.
