### ISSUE TITLE
Spiegel vs directly accessing /_db_updates?

### ISSUE THREAD

**Issue by kripper** [redgeoff/spiegel#220]
If we just need to listen to global changes (and run a script each time a new document is created/updated/deleted somewhere), what benefits offers Spiegel vs just directly accessing `/_db_updates` (live) and then checking each DB `/_changes` feed?

(No replication is required)

**Comment by lostnet** [comment]
### To summarize spiegel's handling for on_change documents:

The spiegel update listener is accessing the '_db_updates' feed to mark change-listener 'cl' documents in the spiegeldb as dirty for any dbs that were updated and are being watched, aside from marking these meta documents it is keeping its meta bookmark for where it is in the global changes so that it does not rerun the feed when it is restarted, nor miss changes while it is stopped.

The change listener watches the spiegel db for cl documents becoming dirty, (locks them) and runs the watched db's changes between the old cl bookmark and its latest change through whatever web service(s) the on_change documents matching the database indicate, then it updates the cl document with the new position (unlocks them) and marks them clean.

### So:

You can naturally mix any parts of this with your own pieces or changes to either of the two listeners or try to make something similar to the update listener but that handles its own logic or storage for how/where to start re-examining feeds from, what to call for each change and how to support multiple listeners if needed. Spiegel is just a definition of how this can be done using a couchdb to store the necessary metadata (interprocess and configuration,) reference implementations for each of the needed listeners in its definition, test suites for them, etc.

**Comment by kripper** [comment]
Thanks will,

> The spiegel update listener is accessing the '_db_updates' feed to mark change-listener 'cl' documents in the spiegeldb as dirty for any dbs that were updated and are being watched, aside from marking these meta documents it is keeping its meta bookmark for where it is in the global changes so that it does not rerun the feed when it is restarted, nor miss changes while it is stopped.

Ok. Basically Spiegel keeps record of changed DBs and the last sync'ed sequence for each DB and CL.

> The change listener watches the spiegel db for cl documents becoming dirty, (locks them) and runs the watched db's changes between the old cl bookmark and its latest change through whatever web service(s) the on_change documents matching the database indicate, then it updates the cl document with the new position (unlocks them) and marks them clean.

Ok. The CLs then check the CL-docs instead of listening the `/_db_updates`.
So basically Spiegel acts like a cache for `/_db_updates` and there is a real benefit if we have **many CLs** right?
Specifically the benefit is when **many CLs** will check changes on-demand and not in a streaming fashion.

If the use case is 1 CL running a web-service each time a couch doc is created/modified/deleted (in a streaming fashion), maybe Spiegel is not really required, unless those web-servcies have to be executed **on a specific node** that could go offline, in which case each node would benefit from having a CL to resume processing pending changes later on demand.

Please correct me if I'm missing something.

**Comment by lostnet** [comment]
> If the use case is 1 CL running a web-service each time a couch doc is created/modified/deleted (in a streaming fashion), maybe Spiegel is not really required, unless those web-servcies have to be executed on a specific node that could go offline, in which case each node would benefit from having a CL to resume processing pending changes later on demand.

Yes, though spiegel is making sure your processing succeeds on each relevant change at least once, and trying to make that mostly just once verse needing to reprocess all past changes in a db at the same time to be sure they were processed at least once after a total restart, etc. (It also makes it easy to manipulate this state if you need to partially reprocess after a change to your service, etc.) If you just watch the `/global_changes?since=now` and for each update doc change run` /[updatedb]/_changes?since=now&descending=true&limit=1` no persistent references to positions in any feeds are necessary in the process, but that's the other end of the spectrum on guarantees and it would be necessary to limit what clients can do, how quickly, etc, if you want to be  sure every change gets processed at least once. If you have very little data, it might be fine to run every feed over again from the start all the time (or more reasonably at every process restart&reboot by having references only in memory,) which guarantees everything gets seen at least once like spiegel, but is the opposite end of the spectrum on avoiding unnecessary reprocessing.

**Comment by kripper** [comment]
Well, when I said "in a streaming fashion" I didn't mean to do "?since=now" (miss the last changes) or "?since=0" (reprocess all). Keeping position references (update sequences) for each database is something I would consider mandatory.

By "in a streaming fashion" I meant a use case where it doesn't happen (under normal circumstances) that a CL goes offline while other CLs are online. In case a node goes offline, it's ok to stop the whole sync process and later resume starting from the last completely processed update-sequence. If the system crashes or is restarted, it could happen that some changes will be reprocessed, but that would be fine too. Probably also happens with Spiegel if no strict consistency is implemented in all pieces.

In summary, I believe that the critical requirement (where Spiegel starts to be really needed) is when 1) we have many CLs and 2) the CLs use to go offline by design and 3) a CL cannot be replaced by other CL (eg: data must be stored on a specific node).

If CLs are online all the time under normal circumstances, the UL (update listener) could just trigger the same actions on the CLs without the need for the CLs to listen changes. They wouldn't be listeners at all, just regular worker nodes executing some webservice. The UL wouldn't need to track  `/_db_updates` sequences for each CL (only 1 for the UL). Tracking `/_changes` sequences would still be required for each CL and database.

The last criteria 3) "_and cannot be replaced by other CL_" is valid because if one CLs goes down and the changes cannot be processed on other CL, it means that this CL will have to resume and process pending changes later, so Spiegel's design will be useful to know which databases are dirty **for this specific CL**.

**Comment by lostnet** [comment]
> The UL wouldn't need to track /_db_updates sequences for each CL (only 1 for the UL).
 
I'm not sure what you mean here. In a given spiegeldb there's only one global_changes position that ULs are trying to update and marking CL documents as dirty based one logical run through the global changes feed. This is sufficient to make sure the 1-n CL processes collectively look at each db that has been updated and bring their position in each up to date.

That one process could be both the CL and UL is a possible design that is simpler for us to reason about in a small non-cluster configuration but isn't really relevant to most use cases. One needs 3+ nodes, in choosing them, they have a maximum capacity that is important. Having 1-3 processes as the minimum is all the same, being stuck with a process that needs to both track the global_changes and use resources for the work is not good when it comes time to get to the maximum the cluster can handle.

> Spiegel's design will be useful to know which databases are dirty for this specific CL.

Every CL process is able to take every job, with 1 spiegeldb only 1 process can be working 1 db at a time as it has the only cl document for the db, a webservice being contacted might be shared or each might be talking to a localhost and on different nodes. I think it is completely unlike "3)" to assume the http process is the couchdb itself again and you want no single point of failure and to know what to do when any 1 of your nodes permanently ceases to exist, you have to implement everything in the spiegeldb either in couchdb which is logical or using something like rsync with the same redundancy configuration as your db, which is repeating yourself.

I only work with clusters, so maybe there's another design that makes sense for single nodes with 2gb RAM or less.. But in general once your data that will have to be persistent looks like spiegel's the design decisions are bike shedding spiegel. It could do something that does better on lots of global_changes updates and no actual work, it could do something that does better on lots of work for relatively few db changes.. You can tune the 2 types of spiegel processes needed and distribute them around among your nodes, and spiegel handles the use case well enough while not needing a different design for a different work load.

It seems to me like you've latched on to a particular configuration of spiegel processes and what it might be good for, but the significant thing is that the accounting for data and processing needs to be managed and persisted, while the processes involved and how you may have been moving them about is not invalidating the incremental processing so far.

**Comment by kripper** [comment]
> I'm not sure what you mean here.

I mean that the UL is tracking dirty databases for each CL, right?
I imagined the CL-docs to be like a list of changed databases and that this list is exclusive for each CL, since each CL may subscribe to different databases. And I understand that the CL then fetch the changed docs directly from the Couchdb servers, right?

**Comment by lostnet** [comment]
> I mean that the UL is tracking dirty databases for each CL, right?

The UL is watching only `updated:[dbname]` records of the global feed, and can find its exact spiegel's CL doc for that database to mark dirty. If the CL doc doesn't exist it needs to figure out if one or more on_change#db_name regex matches and then create that cldoc for the exact db. Note the [update#db_name](https://github.com/redgeoff/spiegel/blob/master/DESIGN.md#on_change) is the user provided regex while the created [cl doc](https://github.com/redgeoff/spiegel/blob/master/DESIGN.md#change_listener) is tracking only 1 last_seq, and is using this to get the records unique _id, so cl_doc#db_name is exactly one db.

> I imagined the CL-docs to be like a list of changed databases and that this list is exclusive for each CL, since each CL may subscribe to different databases. And I understand that the CL then fetch the changed docs directly from the Couchdb servers, right?

CL processes are a pool of workers watching for dirty+unlocked cl documents. If a process grabs one it can progress from the feed relative to /dbname/_changes?since=last_seq by getting each document through all matching on_changes. Since CL docs are per db, any dbs cl doc and processing is progressing at most 100(batch-size) records at a time toward its last_seq on the CL process that has sucessfully gotten its lock.

This is style of change feed processing is very much like functional reactive systems, you might have a lot of new documents or you might have repeated edits, but reprocessing (i.e. by deleting a cl doc) later is very much like replaying the whole sequence of events without time gaps making its pretty easy to verify functional equivalences.

**Comment by kripper** [comment]
Thanks for the detailed explanation.
The design considers that each document is only processed **once** by **any** CL?
Or does it also support that all CLs process a changed document once?

**Comment by redgeoff** [comment]
Awesome discussion here!

**Comment by lostnet** [comment]
> Or only one per each DB?

There's only one CL doc per db. The collection of processes is making sure the work you describe in on_changes documents happen whether you create 1 of each or 1000 of each. If you want to do 2 calls per document you have 2 different on_change documents, one CL process has the lock and sees the change and needs to make both calls. If that one were to crash between these two calls, the cl doc eventually becomes available again and another CL process does both calls to progress the cl doc toward clean.

 > taking care to not have two workers processing the same database at the same time, instead of having the CL processes "asking the UL" which DBs are dirty and not locked.

The synchronization of two processes that do everything is going to be complicated. They still have to know where the other one stopped in each db to not always process the same things twice, even if one db is constantly repeating the global feed. That is all the data in the cl docs, you have to be checking that all the time before starting on a processing a db, so your processes are again watching a cl doc view feed. They need to know whether the other process is handling a portion of the global_feed, so that is the global sequence tracking. A web sevice can cause delays, leaks of sockets, etc, a process will crash, lose routing or become unresponsive. Having the processes that crashed having a combination of locks for portions of the global feed and individual databases adds to the complexity of recovery, so the question is not why are these separate, but why would they not be?

When work is clearly different and well defined its pretty normal to create a separate pool of workers for it especially if you plan to create a system that can correctly scale on post SMP machines. There are also a lot of attempts to take single threaded things as a start and then try to make them keep working while adding copies. But why do that intentionally?
